import Container from "../components/Container";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function ResearchProblem() {
  return (
    <main className="min-h-screen bg-[#fafaf7] text-[#111111]">
      <Navbar />
      <Container>
        <div className="py-20">
          <h1 className="max-w-3xl text-[34px] font-semibold leading-[1.02] tracking-[-0.045em] text-black sm:text-[42px] lg:text-[56px] mb-8">
            Research Problem
          </h1>

          <div className="space-y-8">
            <p className="w-full text-[14px] leading-7 text-black/70 mb-6">
              The research problem revolves around addressing gaps in existing observability frameworks for microservice-based architectures. Traditional tools often lack the adaptability, contextual understanding, and integration required to effectively monitor complex systems. The goal of this research is to propose a Smart Observability Middleware that leverages intelligent automation and machine learning to address these challenges through four autonomous agents.
            </p>

            <h2 className="text-[24px] font-semibold text-black mb-4">
              1. Metric & Signal Discovery Agent
            </h2>
            <p className="w-full text-[14px] leading-7 text-black/70 mb-6">
              The first research gap identified lies in the difficulty of effectively identifying and discovering relevant metrics across rapidly evolving microservice landscapes. Current practices rely on manual instrumentation, which is prone to omissions and inconsistencies. The Metric & Signal Discovery Agent (MSDA) addresses this by autonomously discovering key performance indicators (KPIs) at both the code and runtime levels. This agent uses program analysis techniques, including static and dynamic analysis, to identify missing or underutilized metrics, ensuring a comprehensive telemetry foundation for monitoring.
            </p>

            <h2 className="text-[24px] font-semibold text-black mb-4">
              2. Log Structuring & Enrichment Agent
            </h2>
            <p className="w-full text-[14px] leading-7 text-black/70 mb-6">
              The second gap exists in the unstructured nature of logs generated by microservice systems. These logs are difficult to process and analyze using traditional methods. The Log Structuring & Enrichment Agent (LSEA) addresses this challenge by converting unstructured log data into semantically enriched, structured formats. Through advanced techniques like template mining and semantic classification, the LSEA ensures that logs contain meaningful context, such as trace identifiers, that facilitate cross-service debugging and incident diagnosis.
            </p>

            <h2 className="text-[24px] font-semibold text-black mb-4">
              3. Adaptive Alert Tuning Agent
            </h2>
            <p className="w-full text-[14px] leading-7 text-black/70 mb-6">
              Alert fatigue is another critical issue with current observability systems, caused by the excessive volume of non-actionable alerts. The Adaptive Alert Tuning Agent (AATA) aims to mitigate this issue by employing a self-healing feedback loop that adjusts alert thresholds based on historical incident data and operator feedback. By using machine learning models, AATA reduces false positives and ensures that alerts are meaningful and actionable. This adaptive system evolves over time, learning from previous alerts to optimize future responses.
            </p>

            <h2 className="text-[24px] font-semibold text-black mb-4">
              4. Anomaly Detection & Insight Agent
            </h2>
            <p className="w-full text-[14px] leading-7 text-black/70 mb-6">
              Traditional anomaly detection methods often lack context and operate on isolated signals, such as metrics or logs. The Anomaly Detection & Insight Agent (ADIIA) solves this by correlating anomalies across multiple telemetry sources (metrics, logs, and traces). By using machine learning techniques like Random Forests and Isolation Forest, ADIIA generates actionable incident insights, identifying the root cause and cascading effects of system failures. This allows operators to respond more quickly and effectively to incidents.
            </p>

            <h2 className="text-[24px] font-semibold text-black mb-4">
              Formal Formulation of the Research Problem
            </h2>
            <p className="w-full text-[14px] leading-7 text-black/70 mb-6">
              The core research problem is the need for a unified, adaptive middleware framework that can autonomously transform siloed, noisy telemetry into actionable, context-rich observability insights. Modern microservice architectures generate vast amounts of heterogeneous data, but the tools to process and interpret this data are often fragmented, reactive, and manually intensive. The research aims to bridge these gaps by addressing the following challenges:
            </p>

            <ul className="list-disc list-inside text-black/70 space-y-2">
              <li>Automatically discover and configure missing KPIs at both the code and runtime levels to eliminate telemetry blind spots without manual intervention.</li>
              <li>Shift from static, rigid alerting to adaptive, feedback-driven mechanisms that continuously refine thresholds based on historical operator responses.</li>
              <li>Synthesize fragmented anomalies across disparate telemetry streams into coherent, actionable narratives that explain the root cause and impact of system incidents.</li>
            </ul>

            <h2 className="text-[24px] font-semibold text-black mb-4">
              Research Objectives and Solution
            </h2>
            <p className="w-full text-[14px] leading-7 text-black/70 mb-6">
              The primary objective of this research is to develop and implement a Smart Observability Middleware that enhances monitoring and reliability in microservice-based systems through intelligent automation and machine learning. The goal is to address the gaps identified above and provide a solution that autonomously discovers relevant telemetry, tunes alert thresholds based on feedback, and correlates anomalies across multiple data sources to generate coherent incident narratives.
            </p>

            <div className="bg-gray-50 p-6 rounded-lg mt-8">
              <h3 className="text-[18px] font-semibold text-black mb-3">
                References
              </h3>
              <ul className="list-disc list-inside text-black/70 space-y-2">
                <li><a href="https://arxiv.org/abs/2302.06648" target="_blank" rel="noopener noreferrer">Zhang & Wu (2021) - "Prototype-Level Automation for Cloud Observability"</a></li>
                <li><a href="https://techscience.com" target="_blank" rel="noopener noreferrer">DeepLog: Anomaly Detection and Diagnosis from System Logs through Deep Learning</a></li>
                <li><a href="https://github.com/logpai/Drain3" target="_blank" rel="noopener noreferrer">Drain3: Robust Streaming Log Template Miner</a></li>
                <li><a href="https://researchgate.net" target="_blank" rel="noopener noreferrer">MicroHECL: High-Efficient Root Cause Localization</a></li>
                <li><a href="https://techrxiv.org" target="_blank" rel="noopener noreferrer">Nezha: Fine-Grained Root Causes Analysis for Microservices</a></li>
              </ul>
            </div>
          </div>
        </div>
      </Container>
      <Footer />
    </main>
  );
}